library("riem")
context("climate")
test_that("riem_climate returns the right output", {
  skip_on_cran()
  output <- riem_climate()
  expect_is(output, "data.frame")
  expect_is(output$Place, "character")
  expect_is(output$StationID, "character")
  expect_is(output$Years, "integer")
  expect_is(output$AvgHighTemp, "numeric")
  expect_is(output$MaxHighTemp, "numeric")
  expect_is(output$YearMaxHighTemp, "character")
  expect_is(output$MinHighTemp, "numeric")
  expect_is(output$YearMinHighTemp, "character")
  expect_is(output$AvgLowTemp, "numeric")
  expect_is(output$MaxLowTemp, "numeric")
  expect_is(output$YearMaxLowTemp, "character")
  expect_is(output$MinLowTemp,"numeric")
  expect_is(output$YearMinLowTemp, "character")
  expect_is(output$AvgPrecip, "numeric")
  expect_is(output$MaxPrecip, "numeric")
  expect_is(output$YearMaxPrecip, "character")

  output2 <- riem_climate("ME", "Barnard")
  expect_is(output2, "data.frame")
  expect_is(output2$Place, "character")
  expect_is(output2$StationID, "character")
  expect_is(output2$Years, "integer")
  expect_is(output2$AvgHighTemp, "numeric")
  expect_is(output2$MaxHighTemp, "numeric")
  expect_is(output2$YearMaxHighTemp, "character")
  expect_is(output2$MinHighTemp, "numeric")
  expect_is(output2$YearMinHighTemp, "character")
  expect_is(output2$AvgLowTemp, "numeric")
  expect_is(output2$MaxLowTemp, "numeric")
  expect_is(output2$YearMaxLowTemp, "character")
  expect_is(output2$MinLowTemp,"numeric")
  expect_is(output2$YearMinLowTemp, "character")
  expect_is(output2$AvgPrecip, "numeric")
  expect_is(output2$MaxPrecip, "numeric")
  expect_is(output2$YearMaxPrecip, "character")
  expect_equal(nrow(output2), 1)

  output3 <- riem_climate("MT")
  expect_is(output3, "data.frame")
  expect_is(output3$Place, "character")
  expect_is(output3$StationID, "character")
  expect_is(output3$Years, "integer")
  expect_is(output3$AvgHighTemp, "numeric")
  expect_is(output3$MaxHighTemp, "numeric")
  expect_is(output3$YearMaxHighTemp, "character")
  expect_is(output3$MinHighTemp, "numeric")
  expect_is(output3$YearMinHighTemp, "character")
  expect_is(output3$AvgLowTemp, "numeric")
  expect_is(output3$MaxLowTemp, "numeric")
  expect_is(output3$YearMaxLowTemp, "character")
  expect_is(output3$MinLowTemp,"numeric")
  expect_is(output3$YearMinLowTemp, "character")
  expect_is(output3$AvgPrecip, "numeric")
  expect_is(output3$MaxPrecip, "numeric")
  expect_is(output3$YearMaxPrecip, "character")

  output4 <- riem_climate("NY", "NY5801", is_station_id = TRUE)
  expect_is(output4, "data.frame")
  expect_is(output4$Place, "character")
  expect_is(output4$StationID, "character")
  expect_is(output4$Years, "integer")
  expect_is(output4$AvgHighTemp, "numeric")
  expect_is(output4$MaxHighTemp, "numeric")
  expect_is(output4$YearMaxHighTemp, "character")
  expect_is(output4$MinHighTemp, "numeric")
  expect_is(output4$YearMinHighTemp, "character")
  expect_is(output4$AvgLowTemp, "numeric")
  expect_is(output4$MaxLowTemp, "numeric")
  expect_is(output4$YearMaxLowTemp, "character")
  expect_is(output4$MinLowTemp,"numeric")
  expect_is(output4$YearMinLowTemp, "character")
  expect_is(output4$AvgPrecip, "numeric")
  expect_is(output4$MaxPrecip, "numeric")
  expect_is(output4$YearMaxPrecip, "character")
  expect_equal(nrow(output4), 1)


}
)

test_that("riem_climate outputs warning if no results",{
  skip_on_cran()
  expect_warning(riem_climate("AK"),
                 "No results for this query.")
  expect_warning(riem_climate(the_place = "Stow"),
                 "No results for this query")
  expect_warning(riem_climate(the_state = "FL", the_place = "testID", is_station_id = TRUE))

})
