library("riem")
context("climate")
test_that("riem_climate_coop returns the right output", {
  skip_on_cran()
  output <- riem_climate_coop(state = "MA")
  expect_is(output, "data.frame")
  expect_is(output$Place, "character")
  expect_is(output$StationID, "character")
  expect_is(output$Years, "integer")
  expect_is(output$AvgHighTemp, "numeric")
  expect_is(output$MaxHighTemp, "numeric")
  expect_is(output$YearMaxHighTemp, "character")
  expect_is(output$MinHighTemp, "numeric")
  expect_is(output$YearMinHighTemp, "character")
  expect_is(output$AvgLowTemp, "numeric")
  expect_is(output$MaxLowTemp, "numeric")
  expect_is(output$YearMaxLowTemp, "character")
  expect_is(output$MinLowTemp,"numeric")
  expect_is(output$YearMinLowTemp, "character")
  expect_is(output$AvgPrecip, "numeric")
  expect_is(output$MaxPrecip, "numeric")
  expect_is(output$YearMaxPrecip, "character")
  expect_is(output$Date, "character")

  output2 <- riem_climate_coop("Barnard", "ME", is_station_id = FALSE)
  expect_is(output2, "data.frame")
  expect_is(output2$Place, "character")
  expect_is(output2$StationID, "character")
  expect_is(output2$Years, "integer")
  expect_is(output2$AvgHighTemp, "numeric")
  expect_is(output2$MaxHighTemp, "numeric")
  expect_is(output2$YearMaxHighTemp, "character")
  expect_is(output2$MinHighTemp, "numeric")
  expect_is(output2$YearMinHighTemp, "character")
  expect_is(output2$AvgLowTemp, "numeric")
  expect_is(output2$MaxLowTemp, "numeric")
  expect_is(output2$YearMaxLowTemp, "character")
  expect_is(output2$MinLowTemp,"numeric")
  expect_is(output2$YearMinLowTemp, "character")
  expect_is(output2$AvgPrecip, "numeric")
  expect_is(output2$MaxPrecip, "numeric")
  expect_is(output2$YearMaxPrecip, "character")
  expect_equal(nrow(output2), 1)
  expect_is(output2$Date, "character")


  output3 <- riem_climate_coop(state = "ID", the_date = "2018-07-04")
  expect_is(output3, "data.frame")
  expect_is(output3$Place, "character")
  expect_is(output3$StationID, "character")
  expect_is(output3$Years, "integer")
  expect_is(output3$AvgHighTemp, "numeric")
  expect_is(output3$MaxHighTemp, "numeric")
  expect_is(output3$YearMaxHighTemp, "character")
  expect_is(output3$MinHighTemp, "numeric")
  expect_is(output3$YearMinHighTemp, "character")
  expect_is(output3$AvgLowTemp, "numeric")
  expect_is(output3$MaxLowTemp, "numeric")
  expect_is(output3$YearMaxLowTemp, "character")
  expect_is(output3$MinLowTemp,"numeric")
  expect_is(output3$YearMinLowTemp, "character")
  expect_is(output3$AvgPrecip, "numeric")
  expect_is(output3$MaxPrecip, "numeric")
  expect_is(output3$YearMaxPrecip, "character")
  expect_is(output3$Date, "character")
  expect_equal(output3$Date[1], "Jul 04")

  output4 <- riem_climate_coop("NY5801", is_station_id = TRUE)
  expect_is(output4, "data.frame")
  expect_is(output4$Place, "character")
  expect_is(output4$StationID, "character")
  expect_is(output4$Years, "integer")
  expect_is(output4$AvgHighTemp, "numeric")
  expect_is(output4$MaxHighTemp, "numeric")
  expect_is(output4$YearMaxHighTemp, "character")
  expect_is(output4$MinHighTemp, "numeric")
  expect_is(output4$YearMinHighTemp, "character")
  expect_is(output4$AvgLowTemp, "numeric")
  expect_is(output4$MaxLowTemp, "numeric")
  expect_is(output4$YearMaxLowTemp, "character")
  expect_is(output4$MinLowTemp,"numeric")
  expect_is(output4$YearMinLowTemp, "character")
  expect_is(output4$AvgPrecip, "numeric")
  expect_is(output4$MaxPrecip, "numeric")
  expect_is(output4$YearMaxPrecip, "character")
  expect_equal(nrow(output4), 1)
  expect_is(output4$Date, "character")

  output5 <- riem_climate_coop("AZTPHX", "AZ", the_date = "05-01", is_station_id = TRUE)
  expect_is(output5, "data.frame")
  expect_is(output5$Place, "character")
  expect_is(output5$StationID, "character")
  expect_is(output5$Years, "integer")
  expect_is(output5$AvgHighTemp, "numeric")
  expect_is(output5$MaxHighTemp, "numeric")
  expect_is(output5$YearMaxHighTemp, "character")
  expect_is(output5$MinHighTemp, "numeric")
  expect_is(output5$YearMinHighTemp, "character")
  expect_is(output5$AvgLowTemp, "numeric")
  expect_is(output5$MaxLowTemp, "numeric")
  expect_is(output5$YearMaxLowTemp, "character")
  expect_is(output5$MinLowTemp,"numeric")
  expect_is(output5$YearMinLowTemp, "character")
  expect_is(output5$AvgPrecip, "numeric")
  expect_is(output5$MaxPrecip, "numeric")
  expect_is(output5$YearMaxPrecip, "character")
  expect_equal(nrow(output5), 1)
  expect_is(output5$Date, "character")
  expect_equal(output5$Date[1], "May 01")

  output6 <- riem_climate_coop("NY5801")
  expect_is(output6, "data.frame")
  expect_is(output6$Place, "character")
  expect_is(output6$StationID, "character")
  expect_is(output6$Years, "integer")
  expect_is(output6$AvgHighTemp, "numeric")
  expect_is(output6$MaxHighTemp, "numeric")
  expect_is(output6$YearMaxHighTemp, "character")
  expect_is(output6$MinHighTemp, "numeric")
  expect_is(output6$YearMinHighTemp, "character")
  expect_is(output6$AvgLowTemp, "numeric")
  expect_is(output6$MaxLowTemp, "numeric")
  expect_is(output6$YearMaxLowTemp, "character")
  expect_is(output6$MinLowTemp,"numeric")
  expect_is(output6$YearMinLowTemp, "character")
  expect_is(output6$AvgPrecip, "numeric")
  expect_is(output6$MaxPrecip, "numeric")
  expect_is(output6$YearMaxPrecip, "character")
  expect_equal(nrow(output6), 1)
  expect_identical(output4, output6)

}
)

test_that("riem_climate_coop outputs warning if no results",{
  skip_on_cran()
  expect_warning(riem_climate_coop("AK"),
                 "No results for this query.")
  expect_warning(riem_climate_coop("Barnard", "ME",
                  "No results for this query."))
  expect_warning(riem_climate_coop(place = "Stow"),
                 "No results for this query")
  expect_warning(riem_climate_coop(state = "FL", place = "testID", is_station_id = TRUE))

})
